### ISSUE TITLE
New Scaling

### ISSUE THREAD

**Issue by CaptMir** [ianespana/ShawzinBot#17]
Hey they've add a new scale today you've probs seen it by now but it kinda messes with every thing  notes don't seem to transition the same way as they did before i.e. different notes are being played instead of the correct ones

**Comment by Rareat** [comment]
I think 
"private static int scaleSize = 8;" is the line causing the problem as they are 9 scales now, unless that's for the notes. But i can't test is, because i have an error at every "get => =\=" expecting a { or ; , so i can't fix it myself without causing more problems actually (fuck you visual studio) xD

**Comment by xSimone** [comment]
Confirmed. New Scale 'Yo' is messing everything up. :f

**Comment by ianespana** [comment]
Will publish a fix today

**Comment by VanStorm** [comment]
@Rareat there is more to that. You also need to shift every 7 to 8 and the 6 to 7 in this section:
private static Dictionary<int, int[]> shawzinNotes = new Dictionary<int, int[]>
        {

I created a pull request with the fix :)

**Comment by ianespana** [comment]
Updated, issue closed
