### ISSUE TITLE
Newest version skips too many notes

### ISSUE THREAD

**Issue by Zhuinden** [ianespana/ShawzinBot#19]
Hello!

I'm trying out the new version with the new scaling, but it's skipping a bunch of notes. Is this because of the new scale, or because of some shawzin note limitation?

Hopefully not the second, because then DE is flat out evil having ruined my ability to play songs I make with MIDI... :disappointed:

**Comment by Virg099** [comment]
Yeah it's because the new scale messes the program up when cycling the scales, so say it changes to  major scale, and when it wants to go back to chromatic, it ends up on pentatonic minor instead. Don't worry DE's stance isn't to ban automated shawzin, they are just expanding the notes which just so happens to break the current bot.

**Comment by ianespana** [comment]
@Zhuinden DE introduced a 30 notes per second cap, so if you're playing anything faster than that it'll skip notes. There's no way around this other than to slow down the song.

@Virg099 The newest version I published yesterday fixes this, so it's not the cause anymore

**Comment by Zhuinden** [comment]
@ianespana in my song, there's only 5 notes at most at the same time, yet they get skipped quite  a lot. I think when they said "notes", they actually implemented key presses, potentially breaking all macros.

Slowing down the song doesn't actually make the notes not get skipped. I tried.

**Comment by ianespana** [comment]
If it's key presses then we can't really do much, since we need to press tab a lot of times to change scale to be able to play all notes.
